site_name: HackerPath of TimeLess613
# site_url:
# site_description:
site_author: TimeLess613
repo_name: TimeLess613/kiwi
repo_url: https://github.com/TimeLess613/kiwi
edit_uri: https://github.com/TimeLess613/kiwi/tree/main/docs
# copyright:

nav:
  - Home: index.md
  - 信息收集: 
      - 思路: InformationGathering/summary.md
      - 被动: InformationGathering/footprinting.md
      - 主动: InformationGathering/scan.md
  - 访问&提权: GainingAccess/waiting.md
  - 权限维持: MaintainingAccess/waiting.md
  - 痕迹清理: ClearingTracks/waiting.md
  - About: about.md


theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  # logo: static/img/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
  - search
  # - minify:
  #     minify_html: true