site_name: HackerPath
# site_url:
# site_description:
site_author: TimeLess613
repo_name: TimeLess613/kiwi
repo_url: https://github.com/TimeLess613/kiwi
edit_uri: https://github.com/TimeLess613/kiwi/tree/main/docs
# copyright:

nav:
  - 主页: 
      - Home: index.md
      - Links: links.md
      - 配色变更: material_color_palette.md
  - 基础概念: BasicConcept/BasicConcept.md
  - 信息收集: 
      - 简介: GatheringInformation/GatheringInformation.md
      - 踩点: GatheringInformation/footprinting.md
      - 扫描: GatheringInformation/scanning.md
      - 枚举: GatheringInformation/enumerate.md
      - 思路: GatheringInformation/summary.md
  - 初始访问: 
      - 简介: GainingAccess/GainingAccess.md
      - WEB: GainingAccess/web.md
  - 提权:
      - 简介: EscalatingPrivilege/EscalatingPrivilege.md
      - Linux: EscalatingPrivilege/waiting.md
      - Windows: EscalatingPrivilege/waiting.md
  - 权限维持: Persistence/Persistence.md
  - 痕迹清理: ClearingTracks/ClearingTracks.md
  - 模块: 
      - nmap: Modules/nmap.md
      - burpsuite: Modules/burpsuite.md
      - metasploit: Modules/metasploit.md
      - enumerate_tools: Modules/enumerate_tools.md
      - sqlmap: Modules/sqlmap.md
  - 靶机WriteUp: 
      - WP模板: WriteUp/WriteUp_template.md
      - HTB_Precious: WriteUp/HTB_Precious.md
      - HTB_Shoppy: WriteUp/HTB_Shoppy.md
      - HTB_Soccer: WriteUp/HTB_Soccer.md
      - HTB_MetaTwo: WriteUp/HTB_MetaTwo.md
      - HTB_Ambassador: WriteUp/HTB_Ambassador.md
      - HTB_APT: WriteUp/HTB_APT.md
      - HTB_MonitorsTwo: WriteUp/HTB_MonitorsTwo.md
      - HTB_Busqueda: WriteUp/HTB_Busqueda.md
      - HTB_PC: WriteUp/HTB_PC.md
      - HTB_Inject: WriteUp/HTB_Inject.md
      - HTB_Stocker: WriteUp/HTB_Stocker.md



theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  # logo: static/img/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
  - glightbox
  - search
  # - minify:
  #     minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
#   - md_in_html
extra_javascript:
  - static/js/extra.js
extra_css:
  - static/css/extra.css