site_name: HackerPath
# site_url:
# site_description:
site_author: TimeLess613
repo_name: TimeLess613/kiwi
repo_url: https://github.com/TimeLess613/kiwi
edit_uri: https://github.com/TimeLess613/kiwi/tree/main/docs
# copyright:

# Naming convention: UpperCamelCase/PascalCase for dir and that's main page. 
nav:
  - 主页: 
      - Home: index.md
      - Links: links.md
      - 配色变更: material_color_palette.md
  - 基础概念: BasicConcept/BasicConcept.md
  - 信息收集: 
      - 简介: InformationGathering/InformationGathering.md
      - 踩点: InformationGathering/footprinting.md
      - 扫描: InformationGathering/scanning.md
      - 枚举: InformationGathering/enumerate.md
      - 思路: InformationGathering/summary.md
  - 初始访问: 
      - 简介: InitialAccess/InitialAccess.md
      - WEB: InitialAccess/web.md
  - 提权:
      - 简介: PrivilegeEscalation/PrivilegeEscalation.md
      - Linux: PrivilegeEscalation/waiting.md
      - Windows: PrivilegeEscalation/waiting.md
  - 后渗透:
      - 权限维持: PostExploitation/Persistence.md
      - 痕迹清理: PostExploitation/ClearingTracks.md
  - Resources: 
      - nmap: Modules/nmap.md
      - Burpsuite: Modules/burpsuite.md
      - Metasploit: Modules/metasploit.md
      - SliverC2: Modules/sliver_c2.md
      - Viper: Modules/viper.md
      - Enumerate_Tools: Modules/enumerate_tools.md
      - sqlmap: Modules/sqlmap.md
      - Tunneling: Modules/tunneling.md
      - iptables: Modules/iptables.md
  - 靶机WriteUp: 
      - WP模板: WriteUp/WriteUp-template.md
      - HTB-Precious: WriteUp/HTB-Precious.md
      - HTB-Shoppy: WriteUp/HTB-Shoppy.md
      - HTB-Soccer: WriteUp/HTB-Soccer.md
      - HTB-MetaTwo: WriteUp/HTB-MetaTwo.md
      - HTB-Ambassador: WriteUp/HTB-Ambassador.md
      - HTB-APT: WriteUp/HTB-APT.md
      - HTB-MonitorsTwo: WriteUp/HTB-MonitorsTwo.md
      - HTB-Busqueda: WriteUp/HTB-Busqueda.md
      - HTB-PC: WriteUp/HTB-PC.md
      - HTB-Inject: WriteUp/HTB-Inject.md
      - HTB-Stocker: WriteUp/HTB-Stocker.md
      - HTB-OnlyForYou: WriteUp/HTB-OnlyForYou.md
      - HTB-Escape: WriteUp/HTB-Escape.md
      - HTB-Topology: WriteUp/HTB-Topology.md
      - HTB-Pilgrimage: WriteUp/HTB-Pilgrimage.md
      - HTB-Sau: WriteUp/HTB-Sau.md
      - HTB-Authority: WriteUp/HTB-Authority.md
      - HTB-Codify: WriteUp/HTB-Codify.md
      - HTB-Hospital: WriteUp/HTB-Hospital.md
      - HTB-Devvortex: WriteUp/HTB-Devvortex.md
      



theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  # logo: static/img/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
  - glightbox
  - search
  - tags
  # - minify:
  #     minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
#   - md_in_html
extra_javascript:
  - static/js/extra.js
extra_css:
  - static/css/extra.css