site_name: HacKnowledgeBase
# site_url:
# site_description:
site_author: TimeLess613
repo_name: TimeLess613/kiwi
repo_url: https://github.com/TimeLess613/kiwi
edit_uri: https://github.com/TimeLess613/kiwi/tree/main/docs
# copyright:


# --- config ---
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github-alt
  # logo: static/img/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - header.autohide
    - toc.follow
  font:
    text: Noto Sans
    code: Source Code Pro

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
#   - md_in_html

plugins:
  - glightbox
  - search:
      lang: 
        - zh
        - ja
        - en
  - tags
  - roamlinks
  # - blog
  # - minify:
  #     minify_html: true

extra_javascript:
  - static/js/extra.js
extra_css:
  - static/css/extra.css

# --- End of config ---



# Naming convention: UpperCamelCase/PascalCase for dir and that's main page. 
nav:
  - Home: 
    - 主页: index.md
    - Tool Links: tool-links.md
    - 配色变更: material-color-palette.md
  - 基础概念: basic-concepts/basic-concepts.md
  - 信息收集: 
    - 简介: information-gathering/information-gathering.md
    - 踩点: information-gathering/footprinting.md
    - 扫描: information-gathering/scanning.md
    - 枚举: information-gathering/enumerate.md
    - 思路: information-gathering/summary.md
  - 初始访问: 
    - 简介: initial-access/initial-access.md
    - WEB: initial-access/web.md
  - 提权:
    - 简介: privilege-escalation/privilege-escalation.md
    - Linux: privilege-escalation/waiting.md
    - Windows: privilege-escalation/waiting.md
  - 后渗透:
    - 权限维持: post-exploitation/Persistence.md
    - 痕迹清理: post-exploitation/ClearingTracks.md
  - 武器库:
    - nmap: arsenal/nmap.md
    - Burpsuite: arsenal/burpsuite.md
    - Metasploit: arsenal/metasploit.md
    - SliverC2: arsenal/sliver-c2.md
    - Viper: arsenal/viper.md
    - Enumerate Tools: arsenal/enumerate-tools.md
    - sqlmap: arsenal/sqlmap.md
    - ldapsearch: arsenal/ldapsearch.md
    - Tunneling: 
      - Tunneling: arsenal/tunneling.md
      - SSH Tunneling: arsenal/SSH Tunneling.md

  - Resources: 
    - 简单网络服务渗透: Resources/simple-network-service.md
    - Network:
      - Email: Resources/Network/Email.md
      - Protocol:
        - SSH: Resources/Network/Protocol/SSH.md
        - LDAP: Resources/Network/Protocol/LDAP.md
        - SNMP: Resources/Network/Protocol/SNMP.md
        - SMTP: Resources/Network/Protocol/SMTP.md
        - DNS: Resources/Network/Protocol/DNS.md
        - NetBIOS: Resources/Network/Protocol/NetBIOS.md
        - Gopher: Resources/Network/Protocol/Gopher.md
    - General:
      - 正则表达式: Resources/General/正则表达式.md
    - API:
      - SASL: Resources/API/SASL.md
    - PKI:
      - 公钥证书: Resources/PKI/公钥证书.md
    - Linux:
      - Linux发行版: Resources/Linux/Linux发行版.md
      - Linux命令: Resources/Linux/Linux命令.md
      - Linux各种括号: Resources/Linux/Linux各种括号.md
      - Linux文件权限: Resources/Linux/Linux文件权限.md
      - 分区: Resources/Linux/分区.md
      - 命令风格: Resources/Linux/命令风格.md
      - 换行符: Resources/Linux/换行符.md
      - 配置Linux图形桌面连接: Resources/Linux/配置Linux图形桌面连接.md
      - iptables: Resources/Linux/iptables.md
  - BlueTeam:
    - Splunk:
      - SPL memo: BlueTeam/Splunk/SPL memo.md
      - Splunk知识点: BlueTeam/Splunk/Splunk知识点.md
      - Knowledge Object: BlueTeam/Splunk/Knowledge Object.md
    - Email安全: BlueTeam/Email安全.md
  - 靶机WriteUp: 
    - WP模板: writeup/active/writeup-template.md
    - HTB-Precious: writeup/retired/HTB-Precious.md
    - HTB-Shoppy: writeup/retired/HTB-Shoppy.md
    - HTB-Soccer: writeup/retired/HTB-Soccer.md
    - HTB-MetaTwo: writeup/retired/HTB-MetaTwo.md
    - HTB-Ambassador: writeup/retired/HTB-Ambassador.md
    - HTB-APT: writeup/retired/HTB-APT.md
    - HTB-MonitorsTwo: writeup/retired/HTB-MonitorsTwo.md
    - HTB-Busqueda: writeup/retired/HTB-Busqueda.md
    - HTB-PC: writeup/retired/HTB-PC.md
    - HTB-Inject: writeup/retired/HTB-Inject.md
    - HTB-Stocker: writeup/retired/HTB-Stocker.md
    - HTB-OnlyForYou: writeup/retired/HTB-OnlyForYou.md
    - HTB-Escape: writeup/retired/HTB-Escape.md
    - HTB-Topology: writeup/retired/HTB-Topology.md
    - HTB-Pilgrimage: writeup/retired/HTB-Pilgrimage.md
    - HTB-Sau: writeup/retired/HTB-Sau.md
    - HTB-Authority: writeup/retired/HTB-Authority.md
    - HTB-Codify: writeup/retired/HTB-Codify.md
    - HTB-Hospital: writeup/retired/HTB-Hospital.md
    - HTB-Devvortex: writeup/retired/HTB-Devvortex.md
    - HTB-Surveillance: writeup/retired/HTB-Surveillance.md
    - HTB-Jab: writeup/retired/HTB-Jab.md
    - HTB-Headless: writeup/retired/HTB-Headless.md
    # - HTB-PermX: writeup/retired/HTB-PermX.md
    # - HTB-Sea: writeup/retired/HTB-Sea.md
  