site_name: HackerPath of TimeLess613
# site_url:
# site_description:
site_author: TimeLess613
repo_name: TimeLess613/kiwi
repo_url: https://github.com/TimeLess613/kiwi
edit_uri: https://github.com/TimeLess613/kiwi/tree/main/docs
# copyright:

nav:
  - Home: index.md
  - 基础概念: BasicConcept/index.md
  - 信息收集: 
      - 简介: GatheringInformation/index.md
      - 踩点: GatheringInformation/footprinting.md
      - 扫描: GatheringInformation/scanning.md
      - 枚举: GatheringInformation/enumerate.md
      - 思路: GatheringInformation/summary.md
  - 初始访问&提权: GainingAccess/waiting.md
  - 权限维持: Persistence/waiting.md
  - 痕迹清理: ClearingTracks/waiting.md
  - 模块: 
      - nmap: Modules/nmap.md
      - metasploit: Modules/metasploit.md
  - 靶机wp: WriteUp/index.md


theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  # logo: static/img/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
  - glightbox
  - search
  # - minify:
  #     minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
#   - md_in_html
extra_javascript:
  - static/js/extra.js
extra_css:
  - static/css/extra.css