site_name: HackerPath
# site_url:
site_author: TimeLess613
repo_url: https://github.com/TimeLess613/kiwi
theme: readthedocs
nav:
  - Home: index.md
  - footprinting: footprinting/nmap.md
  - About: about.md
